---
- command: yum update -y

- command: systemctl stop firewalld

- command: systemctl disable firewalld

- name: Install PostgreSQL server packages
  yum: name={{ postgresqlpackage }} state=present
  
- name: Install PostgreSQL other packages
  yum: name={{ item }} state=present
  with_items:
    - {{ postgresqlpackage }}-server.x86_64
    - {{ postgresqlpackage }}-contrib.x86_64
    - {{ postgresqlpackage }}-devel.x86_64
    - {{ postgresqlpackage }}-libs.x86_64 
    - {{ postgresqlpackage }}-plperl.x86_64
    - {{ postgresqlpackage }}-debuginfo.x86_64

- name: Install PgPool II server packages
  yum: name={{ pgpoolpackage }} state=present

- name: Install PgPool II other packages
  yum: name={{ item }} state=present
  with_items:
    - {{ pgpoolpackage }}-devel.x86_64
    - {{ pgpoolpackage }}-extensions.x86_64
    - {{ pgpoolpackage }}-debuginfo.x86_64

- command: systemctl disable postgresql-11

- command: systemctl disable pgpool-II-11
